.TH Minishell 1 "2025" "Minishell" "User Commands"

.SH NAME
minishell \- a simple Unix mini shell that allows you to run commands with pipes, redirections, and internal commands.

.SH SYNOPSIS
.B Prompt >
.I [command] [option]

.SH DESCRIPTION
minishell is a minimalist shell implemented in C.
It allows users to execute Unix commands, use redirections, pipes, history, aliases and .

.SH FEATURES
.TP
.B ls
Lists the files in the current directory. 
.I -al
with details (permissions, size, date).

.TP
.B ps
Displays the list of processes currently running for the current user.

.TP
.B who
Displays the users currently logged into the system.

.TP
.B pwd
Displays the current directory.

.TP
.B cd [directory]
Changes the current directory.

.TP
.B echo [text]
Displays the entered text. 

.TP
.B export VAR=VALUE
Sets an environment variable.  
Example: 
.B export PATH=/usr/local/bin:$PATH

.TP
.B alias
.I name='command'
Creates an alias for a command.
.Br
Example: 
.B alias ll='ls -al'

.TP
.B exit
Exit the shell.

.TP
.B man ./minishell.1
Open the shell manual.

.SH REDIRECTIONS
minishell supports standard redirections:

.TP
.B >
Redirects the standard output of a command to a file, overwriting its contents if the file already exists.

.TP
.B >>
Redirects standard output to a file at the end of the file.

.TP
.B <
Redirects standard input from a file.

.TP
.B <<
Provides a here document, allowing multi-line input to be passed to a command.

.SH PIPES
minishell supports the pipe `|` to connect the output of one command to the input of another.
minishell also supports logical operators `&&` and `||` to conditionally execute commands based on the success or failure of the previous command.

.SH BACKGROUND
Use `&` at the end of a command to run it in the background.

.SH EXAMPLES

.TP
.B echo Hello World
Displays ‘Hello World’ in the terminal.

.TP
.B export PATH=/usr/local/bin:$PATH
Adds /usr/local/bin to the user's PATH.

.TP
.B alias ll=“ls -al”
Creates an alias `ll` for `ls -al`.

.TP
.B history
Displays the last commands executed.

.TP
.B ls -l
Lists the files in the current directory with details (permissions, size, date).

.SH AUTHOR
Aude Bruant and Sabrina Al Hammuti 
